### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by DiegoGuo** [itbencn/DdddOcr.Net#1]
今天测试了三个（DdddOcr.Net，ddddocr-Sharp-Ex，ddddocrsharp）都跑到同一个位置就出错了
![err](https://github.com/itbencn/DdddOcr.Net/assets/17266057/bb4a4ec5-031e-444f-b687-b201ae9d5ed2)
![kdcs](https://github.com/itbencn/DdddOcr.Net/assets/17266057/7757d6ed-4456-420a-b24a-e5bd28883c48)

**Comment by itbencn** [comment]
参考demo项目,判断一下你的验证码图片具体是什么类型
部分验证码图片可能是gif类型,如果是gif类型请先转成png格式再进行推理

**Comment by Lockey-J** [comment]
convert.todouble这个去掉就行。代码不对。

**Comment by itbencn** [comment]
> convert.todouble这个去掉就行。代码不对。

和`Convert.ToDouble()`关系不大,那个报错主要是因为Mat的长宽都为0,而导致这个的原因就是载入的Mat数据是gif的

**Comment by Lockey-J** [comment]
找到问题了。64改成64d就不会。原因就是2个int类型相除默认结果也是int。你这个分母比分子大。最后得到的是0.几。在int类型相除中就变成了0。导致出错，你改成64d后。将会是double类型。最后就不会出错 了。
